# frozen_string_literal: true

source 'https://rubygems.org'

gem 'colorize'
gem 'terminal-table'

gem 'prawn'
gem 'prawn-table'
gem 'simple_xlsx_reader'

group :development do
  gem 'pry'
  gem 'rubocop'
  gem 'standard'
end
