render:
	ruby main.rb assets/Ordersheet_2023-Lila_Lämmchen.xlsx PREINVOICE2
	ruby main.rb assets/Ordersheet_2023-Moquadrat.xlsx
	ruby main.rb assets/Ordersheet_2023-Räubersachen.xlsx
	ruby main.rb assets/Ordersheet_2023-Making_little_things.xlsx INVOICE 0
